controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix: '/api'
    trailing_slash_on_root: false

#api_login_check:
#    path: /api/login_check

auth:
    path: /auth
    methods: ['POST']